### ISSUE TITLE
Any way of loading local HTML5 without setting up a local webserver?

### ISSUE THREAD

**Issue by dannyflint** [AaronShea/BLUI#101]
Has anybody managed to access a local HTML5 page directly using BLUI? If so please give me some advice. I'm trying to get something setup using construct but local security means it's currently not possible. I don't want to have to link to it over the web. Thanks in advance.

**Comment by AaronShea** [comment]
Using the protocol `blui://` at the start of your URLs will allow you to load content relative to your game directory.

**Comment by xzessmedia** [comment]
1. this issue was no real issue
2. the "issue" has been resolved
3. this issue is nearly 2 years old and should be closed.

if the maintainer needs help, let us help you, but its a waste to abandon it!

**Comment by ashea-code** [comment]
@xzessmedia 

You're needlessly pointing out something.
This project is over 5 years old. I made it in college.
I have a full time job as a tools engineer now.
It's open source. Anyone can contribute. Including you.

If someone wants to take it over, feel free to ask.
