### ISSUE TITLE
"Updating the CEF event loop" How?

### ISSUE THREAD

**Issue by gotwig** [AaronShea/BLUI#14]
Hey, I'm mostly using Blueprints for the game I'm working on, Why is the function BluManager::doBluMessageLoop() not exposed? 

Can I add it to a blueprint function library?

**Comment by gotwig** [comment]
Btw you said "No specific ties to any in game class, simple use Blueprints (or C++) to create a new "BluEye" object and grab its material instance, then you can paint it on anything!" , thats not true..

**Comment by gotwig** [comment]
Ok heres an easier solution, for people with blueprint projects:
Add a new BP Function library. Open the .h file. After Generated_Body() gets called, write this:

Public:
	UFUNCTION(BlueprintCallable, Category = "CustomLibrary")
	static void CefLoop();

Now on the .cpp file add the following code:
At the very top add " #include "Blu/Public/BluManager.h".
Now to implement your new function, add this: 
void UUBP_FuncLib::CefLoop()
{
	BluManager::doBluMessageLoop();
}

To run the loop in your game, call the "CefLoop" node, if you want it all the time, add a new event tick, like in the readme, for your game mode bp, and after that call the CefLoop node.

It works now fine, sry for the confusion before.. it just wasnt very clear to me, I would be glad if you could add this information to the Wiki of the project or something like this. Thanks for your awesome plugin!

**Comment by AaronShea** [comment]
Thanks for the snippet! Would you like to make a pull request with these changes? I'd really appreciate it.

I'm not sure how a bluepring tick call escaped my ideas
