### ISSUE TITLE
UI Widget causes engine crash, tried different embed scenarios

### ISSUE THREAD

**Issue by gotwig** [AaronShea/BLUI#15]
So I have a mainmenu widget with a vertical panel. On the left side I want a seperate website to be displayed in a widget switcher, on the right side another website. Now I tried to switch from a widget switched to "custom created widget" and than tried to drag it in into the canvas, but that caused in both cases, widgetswitcher and the "custom created widget" an engine crash. The base web-canvas widget is the ExampleHUD Widget from master branch.

**Comment by gotwig** [comment]
ok the crash only happens when I go into the view with my mouse cursor.

**Comment by AaronShea** [comment]
Interesting. Could you send the stack trace in a comment here? That'd help me pinpoint the issue

Thanks!

**Comment by gotwig** [comment]
the thing is, the crash report dialog doesnt upen up.

**Comment by AaronShea** [comment]
That's interesting. Try attaching Visual Studio to it (or launching it from VS) and use it for debugging. A screenshot of the break would help as well.

**Comment by gotwig** [comment]
Ok, so it happens for the mouse move and mouse click event. key input doesnt seem to produce it. also the website appears to be completly blank. When i create the widget standalone and add it to viewport, everything works as its supposed to.

**Comment by AaronShea** [comment]
Not sure how to help narrow down exactly the issue, could you provide code/screenshots if you're comfortable with it?

**Comment by gotwig** [comment]
http://i.imgur.com/kTt8cGw.jpg 

I try to debug now with VS for you. Are you in IRC? If you are pls join #unrealengine on Freenode ;X

**Comment by gotwig** [comment]
When I play in an external viewport, everythings working normal :+1:
