### ISSUE TITLE
How to get keyboard input?

### ISSUE THREAD

**Issue by gotwig** [AaronShea/BLUI#16]
I really dont know how?

It seems the two events Get Key Down and Get Event Char are needed, however I dont find a widget which provides those.

**Comment by AaronShea** [comment]
My suggestion would be to create separate widgets for each web panel you are tying to do, and overriding their key input

**Comment by gotwig** [comment]
so basicly creating your own UWidget or what? I dont know how to do this.

**Comment by AaronShea** [comment]
Just creating a new User Widget in editor, spawning those instead of trying to do everything inside one HUD widget

Then handle mouse events in each of them separately.
If you want to keep it one Widget you'll need to do some math to figure out the correct x,y coordinate to give to BLUI
