### ISSUE TITLE
Improve Mouse Click position

### ISSUE THREAD

**Issue by gotwig** [AaronShea/BLUI#17]
I tried to embed multiple html canvas on a mainmenu widget blueprint. But it seems the input gets handled for the whole mainwidget blueprint, instead of only in the area of the html canvas. I wonder what can be done about it :/?

Right now its like you have to click into very weird spots on the screen (example fullhd), and its not where the html content in reality is.

**Comment by AaronShea** [comment]
Once again, separate widgets may help with this, also doing some math will help you get the X,Y to create a vector from, then pass into the mouse methods
