### ISSUE TITLE
Mac and Linux version

### ISSUE THREAD

**Issue by tnako** [AaronShea/BLUI#20]
Hello! Thank you for great plugin! 

Where I can find version for MacOS and Linux, or source code of blu_ue4_process?

**Comment by AaronShea** [comment]
Hello!

At the moment I don't have binaries for Linux or OSX in a fictional state. However Linux support is in the work and OSX will be soon after that. If you're looking for the source code, take a look at: https://github.com/AaronShea/BluBrowser
