### ISSUE TITLE
[LINUX] Chromium Sandbox won't let BLUI run

### ISSUE THREAD

**Issue by gotwig** [AaronShea/BLUI#21]
Hey, when I try to start the editor on linux, I get the error:
"[0305/164432:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0100/000000:ERROR:zygote_linux.cc(585)] write: Broken pipe
"
And the editor wont start up. The project compiled fine (by Clang)

**Comment by AaronShea** [comment]
Running without the sandbox is normal as the sub-process launches with --no-sandbox

As for the broken pipe with the editor, ensure the blu_ue4_process executable is along side the UE4 Editor executable.

If that does not help, I know packaging for Linux from windows (cross-compiling) working perfectly fine. You do need to build the editor from source to include the cross-compiling system.

**Comment by gotwig** [comment]
I added the contents of the shipping linux folder into the binary linux folder, in the same folder like UE4Linux, i made all files in the folder executable as well.

**Comment by AaronShea** [comment]
Interesting, I'll look into this after PAX East this weekend

**Comment by gotwig** [comment]
btw, I try to build under linux for linux.

**Comment by gotwig** [comment]
Adding --no-sandbox as an argument to./blu_ue4_process  fixes the error. the cpp file also calls ./blu_ue4_process  and not ./blu_ue4_process  --no-sandbox !

**Comment by AaronShea** [comment]
Does this stop the editor from crashing at startup?

you simply changed:

```C++
CefString(&BluManager::settings.browser_subprocess_path).FromASCII("./blu_ue4_process");
```

to


```C++
CefString(&BluManager::settings.browser_subprocess_path).FromASCII("./blu_ue4_process --no-sandbox");
```

yeah?

**Comment by gotwig** [comment]
The first error about the sandbox is gone, but i have to test for the pipe error, building on linux is not so easy, please wait a bit :)

**Comment by gotwig** [comment]
No, sry, i cant get it to work:
[0305/193832:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
./blu_ue4_process --no-sandbox

**Comment by AaronShea** [comment]
Well, I'll be looking into it soon then!
Again my advice is to just cross-compile, I've tested that and it works just fine. I'll post updates here as I figure things out

**Comment by gotwig** [comment]
So current situation is, the broken pipe error (second) goes away by passing the command line argument to disable sandbox, but the first error remains. I am not sure how critical those errors are, but the editor windows doesnt open, and the process gets terminated on terminal.

**Comment by AaronShea** [comment]
With the recent updates I've been able to successfully launch the editor in Linux
