### ISSUE TITLE
Unreal ships with CEF,  why doesn't the project take advantage of that?

### ISSUE THREAD

**Issue by afuzzyllama** [AaronShea/BLUI#26]
Looking over this and the UE source.  Why doesn't BLUI take advantage of the CEF that is already distributed with the Unreal Engine?  I see there isn't Linux support in the Engine/Source/ThirdParty/CEF3, but maybe this is something to bring up with Epic?

**Comment by AaronShea** [comment]
The issue is I require modifications to send and recive JavaScript events to and from the engine, these functions are not in the CEF that ships with UE4

**Comment by neico** [comment]
Pretty sure that they improved on that by now: https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/WebBrowser/Private/WebJSScripting.h#L41

**Comment by flufy3d** [comment]
yes ,I found that too

**Comment by AaronShea** [comment]
BLUI will continue to use our own build of CEF. We have many customizations to the build and will also update to the newest releaser of CEF provided everything tests out fine.

If I were to move to UE's built in CEF, a huge amount of code would need to be changed, breaking existing users' projects that use BLUI
