### ISSUE TITLE
How to send Keyinputs without using the UMG Class

### ISSUE THREAD

**Issue by The-Skas** [AaronShea/BLUI#32]
Hey,

At the moment, the blui function KeyDown, takes a KeyEvent as Input. we can only use it if its part of a UMG class (Since it overrides the Keydown method, which already passes a KeyEvent in by default), BUT how do use it if we wan't to call inputs to it directly? (Using Any of the Keyboard nodes in Blueprint (Enter, Shift, A,Z,W,S etc..)

**Comment by AaronShea** [comment]
Hello there! I'll be looking into this as there currently isn't a way to deal with it.

**Comment by The-Skas** [comment]
Awesome, Im taking a look at it as well. Good luck :+1:

**Comment by AaronShea** [comment]
So the latest commit should let you pass and character (like "j" or "k") as well as specify key modifiers using the Raw Character Input node.
As far as things like Escape and Tab etc. I'm still looking into a good solution

**Comment by The-Skas** [comment]
Awesome. Now I can forward keys with ease.

Im curious as to why Escape and Tab are harder to implement though.

Anyway, thanks!

**Comment by AaronShea** [comment]
The issue being in CEF there is a slight difference between character key events and just plain old key events. Fact being we can't get the key code for something like ENTER from any old blueprint.
CEF Event needs the native key code

**Comment by buddytex** [comment]
@AaronShea Hey, I think I have a good solution to the special keys issue, I'll have a pull request in a few minutes.

**Comment by AaronShea** [comment]
Closed by #35
(Testing soon)
