### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by hitchcott** [AaronShea/BLUI#33]
Hi @AaronShea,

Thanks for the plugin, extremely exciting - especially as a web developer.

I was wondering if you could create a step-by-step of installing and using this, as I've tried and failed myself. I tried adding the BLUI plugin to a project, but when I open it I get an error saying `UE4Editor-Blu.dll` is missing, it asks me to rebuild, then fails. I'm using UE Windows x64 build.

The readme says to "copy the folder inside `shipping`" to get started, but I'm not sure where this is (can't find it in the repo).

Apologies for my lack of experience - I've never really developed on a windows system before.

Any help would be appreciated, cheers!

**Comment by hitchcott** [comment]
Ahah, I just found the Wiki!

Might be worth mentioning it in the readme :+1:

**Comment by artigen** [comment]
Visual Studio 2015 show "Version out date , can not compile ....need manually compile"

  Is that mean UE 4.10.3 is too new  and  " Your code is out date "
