### ISSUE TITLE
Syntax error in BluEye.h

### ISSUE THREAD

**Issue by LoveMetal-StrangeGames** [AaronShea/BLUI#38]
I was trying to do a very basic setup with a c++ Actor class, here is the code:
http://pastebin.com/yQq76fbv

And when I built the project, Visual Studio tells me that there are 27 errors inside BluEye.h:
http://pastebin.com/qh2f93V3

I installed BLUI just as you told in the wiki, but as I'm very new to UE4 it would be very likely that the mistake is on my side.

Ty in advance

**Comment by AaronShea** [comment]
Hello!

place this additional include above BluEye.h

```
#include "RenderHandler.h"
```

**Comment by LoveMetal-StrangeGames** [comment]
Thank you, it works fine now!
Is there a way for me to know about missing headers errors? I'd feel bad if I had to pull a github issue every time I encounter an issue like this one!

**Comment by AaronShea** [comment]
@LoveMetal-StrangeGames 
Sorry for the really late reply, started working again!
I'd hit up the forum on the Unreal Engine official forums site. Under released products.
