### ISSUE TITLE
[Mac] UE 4.8 Declaration shadows a field of RenderHandler

### ISSUE THREAD

**Issue by agustindidiego** [AaronShea/BLUI#39]
When trying to compile the Plugin on Unreal Engine 4.8 in a Mac, Xcode returns an error in the RenderHandler.cpp file with the message: Declaration shadows a field of RenderHandler
The error happens because the declaration of the local variables "width" and "height" being named the same as the constructor parameters. I'm not a C++ expert programmer and I doubt why the error is thrown in UE 4.8 but not in UE 4.7, maybe there is some pragma declaration in Unreal code, no idea.

Changing the RenderHandler local variables "with" and "height" names fixes the issue, and the plugin is compiled.

Sorry to not send a PR, I downloaded the plugin package file and I didn't fork the repository.

Files that needs to be updated:

**RenderHandler.h**
change local "width" and "height" variable names to, for example, "_width" and "_height" on lines 22 and 23
**RenderHandler.cpp**
Update local "width" and "height" variable names on lines 5,6,12
**BluEye.cpp**
Update RenderHandler instance "width" and "height" variable names on lines 225,226

Cheers

**Comment by AaronShea** [comment]
That's really bizarre, I'll take a look into that and release a fix!
