### ISSUE TITLE
Can't find Shipping folder

### ISSUE THREAD

**Issue by davesenter** [AaronShea/BLUI#40]
Hello, I am trying to install your plugin but cannot seem to find the shipping folder you mention in the installation instructions. It is not in the folder I downloaded for your plugin, the UE4 project, or UE4 installation folders. Where can I find the shipping folder?

**Comment by AaronShea** [comment]
Did you download from the Releases page?
https://github.com/AaronShea/BLUI/releases
The zip folder will contain 

`Windows Shipping`

`Mac Shipping`

`Linux Shipping`

**Comment by davesenter** [comment]
Yes, I downloaded the zip. Perhaps I am missing something?
![blui_downlaod](https://cloud.githubusercontent.com/assets/11928314/8187998/c33aa396-1418-11e5-9bac-8d16b68f342e.JPG)

**Comment by AaronShea** [comment]
The zip and release zip are different
You need the release zip, click "releases" from the main page and download BLUI.2.5.Release.OSX.Beta.zip

**Comment by davesenter** [comment]
Got it working! Thanks for the help and speedy responses!
