### ISSUE TITLE
LogInit:Warning: Incompatible or missing module: libUE4Editor-Blu.so

### ISSUE THREAD

**Issue by peinguin** [AaronShea/BLUI#41]
Copied "BLUI 2.5 Release OSX Beta/Linux Shipping" to "UnrealEngine-4.8.0-release/Engine/Binaries/Linux/Blu"
"BLUI 2.5 Release OSX Beta/BLUI" to "Plugins"

And after start editor see a message that says "Missing module libUE4Editor-Blu.so".

In compilation process I have an error. 
error: typedef redefinition with different types ('long' vs 'FPlatformTypes::int64' (aka 'long long'))
typedef long                int64;  // NOLINT(runtime/int)
                            ^
Runtime/Core/Public/HAL/Platform.h:601:32: note: previous definition is here
typedef FPlatformTypes::int64           int64;          ///< A 64-bit signed integer.

**Comment by AaronShea** [comment]
Make sure you copy the content of the folder next to the Editor binary, not just the actual shipping folder

**Comment by peinguin** [comment]
Moved content of UnrealEngine-4.8.0-release/Engine/Binaries/Linux/Blu to UnrealEngine-4.8.0-release/Engine/Binaries/Linux
The same. It wants "libUE4Editor-Blu.so".

**Comment by AaronShea** [comment]
Seems there's a compiling error. The plugin usually compiles on a per project basis. So I assume those compile errors are from the project compilation?

**Comment by peinguin** [comment]
I use "UnrealEngine-4.8.0-release". Maybe it is not supported version?

**Comment by AaronShea** [comment]
4.8 does work with the plugin. 
But I will test this later today on Linux

**Comment by AaronShea** [comment]
After looking into it, it seems that CEF is trying to re-declare a typedef that UE4 already has declared. In this case it's uint64. This can be changes with one or two line edits to the header file mentioned in the error message. 

However, even after I changed these lines and fixed another small bug the editor (on Linux) does crash without any error for me to reference. Until I can solve this I highly advise you cross-compile from Windows to Linux as I know fully well this works. The release with fixes is going up now as version 2.6.

**Comment by AaronShea** [comment]
Update! Seems like the weird crash was simply having a blank URL in my project. You should be good to go!
