### ISSUE TITLE
Does it work with Unreal Engine 4.8.1?

### ISSUE THREAD

**Issue by PhilAndrew** [AaronShea/BLUI#42]
Hi there, I followed the instructions.

1. Installed Unreal Engine 4.8.1
2. Place the contents of latest release of BLUI "Windows Shipping" folder into C:\Program Files\Epic Games\4.8\Engine\Binaries\Win64
3. Downloaded your demo application, tried to open it "BLUIDemo.uproject", it asked to rebuild some DLL, I said yes
4. Run demo, no browser showing, just white rectangles where the browser should be

Can I provide more information? What else can I try?

**Comment by AaronShea** [comment]
Hello, something tends to go wrong with the demo project where converting it to a 4.8 project causes the Default URLs of all displays to be lost.

I suggest trying to make your own project, and try BLUI there.

I'll be updating the demo project to repair the conversion soon.

**Comment by PhilAndrew** [comment]
Ok I'll try tomorrow thanks! (its late here)

**Comment by PhilAndrew** [comment]
I don't really understand how to add it to a new project, ... fairly confused. I'm a programmer, I understand code, but I don't know the Unreal UI system. Is there something I can do to the demo project to make the demo project work?

**Comment by trdwll** [comment]
I didn't really read on this much, but this should possibly help you with the installation. https://docs.unrealengine.com/latest/INT/Programming/Plugins/index.html

**Comment by AaronShea** [comment]
Click on each display in the demo in editor. See if the Default URL property is empty

**Comment by AaronShea** [comment]
Closing this for spring cleaning
