### ISSUE TITLE
JQuery rendering/positioning issue

### ISSUE THREAD

**Issue by kitblackheart** [AaronShea/BLUI#43]
Hello and goodnight, 
It seems BLUI has issues with JQuery effects, it seems to be detecting the wrong positions of the HTML elements when I use "mouseenter" or "mouseleave" functions, making it very imprecise, not detecting correctly nor the location or element width/height.

**Comment by AaronShea** [comment]
Hello, could you give me some more information on the issue?
How can I reproduce it and what are the expected results?

**Comment by kitblackheart** [comment]
i wanted to post evidence too, sadly my recording software kinda expired on me (sorry for that)
however, here is my whole HTML folder, to test it, its very simple, you replace the demo folder with this one: https://mega.nz/#!fcoUSDAa!7molOyayn_uOUA_1kIMIm5JxEW-eg0XuYuYCMIJnzhI
launch the project, the BLUI logo in the HUD doesnt work as expected, it shoudl change the opacity to 0.5 when the mouse is not touching it, and 1 when its touching it (it somewhat of works, it just detects the picture in the wrong coordinates).
I am willing to help testing if needed (EMAIL: kitblackheart@gmail.com)

**Comment by AaronShea** [comment]
All coordinates are relative to the UE4 screen space in the demo by default. So clicking on X100 Y200 on the UE4 window will trigger that exact click coordinate in the browser. If you want it to be releative to the actually rendered page, you must check the x,y position on the UMG widget, not on ue4 screen space

**Comment by kitblackheart** [comment]
so technically speaking thats an issue with jquery?
because the functions i used dont require any coordinate arguments, you just call them on the object itself (in this case the img object (the logo))

**Comment by AaronShea** [comment]
It's not an issue with jQuery but with how you're translating the x,y from ue4s screenspace to the browser's

**Comment by AaronShea** [comment]
Closing this for spring cleaning
