### ISSUE TITLE
Click on widget doen't trigger

### ISSUE THREAD

**Issue by kimFrost** [AaronShea/BLUI#49]
When a widget with a click override binding is used, and the unhandled event is returned, the click doens't register, unless the user double clicks 
Tested in UE 4.8.3 with BLUI 3.1

**Comment by AaronShea** [comment]
BLUI has nothing to do with how input is passed. I simply provide methods to trigger clicks, what you do with them is up to you. You don't need to follow the ExampleHUD at all. Properly handling input from UE4 is something that is on a project per project basis.
