### ISSUE TITLE
mouse focus problem

### ISSUE THREAD

**Issue by flufy3d** [AaronShea/BLUI#51]
in the BLUIDemo test-javascript.html,when I shift f1 use mouse to control spin or not ,then I can't go back to the prev state,it seems the blui occupy the mouse never to release it again.

Thanks in advance

**Comment by AaronShea** [comment]
That may be a product of the Blueprint example, not of BLUI.
It only provides methods to trigger clicks and mouse movement using x, y coordinates relative to the rendered page. It is up to you to actually hook and release input the way you want.
