### ISSUE TITLE
Cannot get teh plugin installed

### ISSUE THREAD

**Issue by timothyBrake** [AaronShea/BLUI#53]
This seams like an awesome plugin but I have issues trying to install the plugin in UE4.9.2 (and also 4.8.3). 
1. I did a git checkout of master.
2. Copied the BLUI to the plugin folder of UE (as the docs mention)
3. The docs says: "Copy the files located inside the 'shipping' folder... " but I cannot find the shipping folder in the BLUI branch. So I am not sure what to do here...
4. Start UE4 4.9.2 and enable the plugin.
5. After restart, a popup appears with text "Plugin missing opr incompatible: Missing or incompatible modules in BLUI plugin - would you like to disable it? You will no longer be able to open any assets created using it."

What must I do to use the plugin? Any help is more than welcome

**Comment by AaronShea** [comment]
Please download a zip distribution from the Release pages on Github. The repo does not include the binary files for CEF or the header files

**Comment by timothyBrake** [comment]
Hi,

Thank you for the response but I still get an error. I downloaded the release as you said from here https://github.com/AaronShea/BLUI/releases. Tried installing it but no luck so far... I must be doing something wrong here...
Here is what I did:
1. I removed the plugin from C:...EpicGames/4.9/Engine/Plugins
2. Downloaded the BLUI.3.1.Windows.Linux.CX
3. Unzipped it and copied the complete directory BLUI to C:...EpicGames/4.9/Engine/Plugins
4. Created new empty project with Starter Content
5. Edit > Plugins > UI > Enable BLUI and restart
6. Error: Missing or incompatible modules in BLUI plugin - would you like to disable it? You will no longer ...
7. As it does not work I deleted the BLUI from C:...EpicGames/4.9/Engine/Plugins
8. Copied the BLUI directory in "directory of project" > Plugins 
9. Opened the project
10. Error: "Plugin 'BLUI' failed to load because module 'BLULoader' could not be found. Please ensure the plugin is properly installed, otherwhise consider disabling it..."

I have copied the complete unzipped directory BLUI to the Plugins directory so I am not sure what to do here. Is there a step that I missed? I only did the steps above, so do not assume I did any other steps like copy the something else somewhere, set a flag some where, installed anything else,... 
I would really like to use this awesome plugin! 

Any help is much appreciated.

Kind regards,
T

**Comment by AaronShea** [comment]
You must install the plugin at a project level, not into the Engine's plugin directory.

**Comment by timothyBrake** [comment]
Hi,

I tried that (starting from point 8 in previous comment). I see the README mentions "Re-generate your project's Visual Studio file and load up the editor. Then check the plugin list to ensure it has been loaded!". I do not have Visual Studio as I am just using BluePrints. Maybe that is the issue?

**Comment by AaronShea** [comment]
There is your problem, it needs to be a C++ project to allow the plugin to compile in Visual Studio.

**Comment by timothyBrake** [comment]
Ok thanks, that solved the mystery. Any chance in making this plugin work without the need to compile in Visual Studio?

**Comment by AaronShea** [comment]
It's a code plugin, so it is required that you have visual studio installed, otherwise Unreal could never even compile the project.

**Comment by koras** [comment]
MachineId:08B450454308DFDEFAE79FAD4EF2909E
EpicAccountId:9fea9eb493fa4a7f981b1156273a72d1

Unknown exception - code c06d007e (first/second chance not available)

""

KERNELBASE
UE4Editor_Blu!__delayLoadHelper2() [f:\dd\vctools\delayimp\delayhlp.cpp:323]
UE4Editor_Blu!_tailMerge_libcef_dll()
UE4Editor_Blu!CefStringBase<CefStringTraitsUTF16>::FromWString() [d:\ue4\4.10\last\plugins\blui.3.1.windows.linux.cx.-.vs2015\blui\thirdparty\cef\win\include\internal\cef_string_wrappers.h:605]
UE4Editor_Blu!CefStringBase<CefStringTraitsUTF16>::CefStringBase<CefStringTraitsUTF16>() [d:\ue4\4.10\last\plugins\blui.3.1.windows.linux.cx.-.vs2015\blui\thirdparty\cef\win\include\internal\cef_string_wrappers.h:325]
UE4Editor_Blu!FBlu::StartupModule() [d:\ue4\4.10\last\plugins\blui.3.1.windows.linux.cx.-.vs2015\blui\source\blu\private\blu.cpp:9]
UE4Editor_Core!FModuleManager::LoadModuleWithFailureReason() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\core\private\modules\modulemanager.cpp:438]
UE4Editor_Projects!FModuleDescriptor::LoadModulesForPhase() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\projects\private\moduledescriptor.cpp:370]
UE4Editor_Projects!FPluginManager::LoadModulesForEnabledPlugins() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\projects\private\pluginmanager.cpp:454]
UE4Editor!FEngineLoop::LoadStartupModules() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\launch\private\launchengineloop.cpp:1982]
UE4Editor!FEngineLoop::PreInit() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\launch\private\launchengineloop.cpp:1495]
UE4Editor!GuardedMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\launch\private\launch.cpp:110]
UE4Editor!GuardedMainWrapper() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\buildfarm\buildmachine_++depot+ue4-releases+4.10\engine\source\runtime\launch\private\windows\launchwindows.cpp:200]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll

not compilled (;
