### ISSUE TITLE
Unreal.JS integration 

### ISSUE THREAD

**Issue by paultech** [AaronShea/BLUI#57]
Hello,

Possible enhancement suggestions to interface the JS runtime with https://github.com/ncsoft/Unreal.JS 

Unreal.JS makes use of the UE reflection system so real-time binding can be achieved. I'm mainly interested in this to bind variables between actors <-> BLUI to prevent the constantly execution of javascript functions for updating variables that can quickly get out of sync.

Thanks!

**Comment by AaronShea** [comment]
BLUI and Unreal.js are two very different projects. While they may use a similar javascript engine (V8) BLUI makes use of the entire Chromium Embedded Framework. Interfacing with Unreal.js is something I would consider project specific, and not something I'd really think about putting into BLUI itself. 

You may be able to look at passing/accessing V8 contexts around internally between the two. This would be very possible, but again, is very project specific. I do believe it would be doable with enough effort.
