### ISSUE TITLE
Video tag in web browser not working

### ISSUE THREAD

**Issue by h27han** [AaronShea/BLUI#64]
If you write a simple web page with a video tag, no video will actually be played even though it plays in web browser.

**Comment by AaronShea** [comment]
What type of video are you trying to play?

**Comment by h27han** [comment]
I did both a normal mp4 link and a streaming link like:
https://r2---sn-gvbxgn-t34e.googlevideo.com/videoplayback?pl=16&mime=video%2Fmp4&expire=1452719538&ip=99.236.206.226&key=yt6&dur=170.388&ratebypass=yes&source=youtube&lmt=1433981700634915&requiressl=yes&ipbits=0&signature=D6FB13C3339EBFABEC42194DE6A2DB9CF76B4587.1D5A12B56A7E8D533E831F243D5982DC3C6D64FD&fexp=9406985%2C9416126%2C9420452%2C9422596%2C9423662%2C9427016&sver=3&id=o-APYdpFS8pD_5tbyiHIRgROiSqctw0KGxLxXdlVQdFUaq&mn=sn-gvbxgn-t34e&mm=31&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=x4B3Mr8bHPU&mv=m&mt=1452697765&ms=au&itag=22&initcwndbps=4503750

**Comment by AaronShea** [comment]
The only formats that can be used within BLUI for audio and video tags are WebM and OGG/Vorbis formats. This is due to licensing issues.
