### ISSUE TITLE
Severe mouse lag on low end computer

### ISSUE THREAD

**Issue by javoire** [AaronShea/BLUI#65]
Hey, just wanted to mention that I'm experiencing severe lag with my mouse cursor on a MacBook Pro 2014 `2,8 GHz Intel Core i7` `16 GB 1600 MHz DDR3` `Intel Iris 1536 MB` `UE 4.10.2`

As if the mouse acceleration goes bananas if you move it to fast. It went away when I removed BLUI

Just wanted to mention it, I'm not able to help out at the moment unfortunately.

I think this plugin seems really awesome (and perfect for a webdev like me) to make in game UIs, especially those you put on a material on an actor in the world, as I'm planning to do with my game. If I have time I'll try it out on my windows computer with better perfomance.

Thanks for writing a great plugin

Cheers

**Comment by javoire** [comment]
Maybe #63 would have impact, if reduced footprint means reduced processing of mouse events.

Question, is the mousemovement captured by UE4 then sent to BLUI and forth? Is there extra layers of mouse movement tracking/computing involved with this plugin activated than in "vanilla" UE4?

**Comment by javoire** [comment]
I can add that when I build the game for release, and have higher graphics settings, I experience some mouse lagging as well. So it's probably more of an overall performance issue, and not with this plugin, but it added some weight to my project.

I'm gonna compare with the native UI solutions and check the difference

**Comment by javoire** [comment]
I've been able to reproduce the lag with native UI widgets, so it seems unrelated to this. Switching between hardware and software cursor (shift + F1) has an enormous difference. So it's an engine thing

**Comment by AaronShea** [comment]
Sorry for replying so late, glad you were able to narrow down the issue
