### ISSUE TITLE
Unreal 4 10.3 (last release under 4)

### ISSUE THREAD

**Issue by DunkenKBliths** [AaronShea/BLUI#68]
Was hoping to check your code out...but unfortunately...the plugin wont load under 4.10.3

;-)

**Comment by AaronShea** [comment]
Interesting, I'll have a look at this later today. What are you running ue4 on and do you have any crash logs?

**Comment by DunkenKBliths** [comment]
Hi Aaron...this is a Windows 7 pro machine
can you point me in the direction of the crash log...it didnt crash, it just told me 

![image](https://cloud.githubusercontent.com/assets/12229031/13303385/079a376a-db9f-11e5-8b68-1f0438208c02.png)

**Comment by AaronShea** [comment]
I've just been able to run it over here using the latest release for 4.10.4, I'm getting no issues loading it up over here. Have you downloaded the correct release from the Releases page on Github, or did you just download the source code zip?

**Comment by DunkenKBliths** [comment]
I was running on 4.3 so will upgrade to 4.4 to see if this fixes it...
the version am using is ... BLUI.3.1.Windows.Linux.CX.zip  (I've also tried the Visual 2015 version)

**Comment by DunkenKBliths** [comment]
Ok... I think I might have the answer.... I created my projects from **Blueprint** not **C++** (tab) therefore I don't have the "**.CS**" file in my project to add the **"PublicDependencyModuleNames.AddRange(new string[] { "Blu" });"** too ....

I do see the plugin in the list but still get the "Missing module" error...

**Comment by AaronShea** [comment]
Ah yes, you must start a project as C++ in order to compile the plugin.
This is actually required for all C++ plugins.


- Aaron




---- On Thu, 25 Feb 2016 13:53:39 -0800 Dunken K Bliths &lt;notifications@github.com&gt;wrote ---- 




Ok... I think I might have the answer.... I created my projects from Blueprint not C++ (tab) therefore I don't have the ".CS" file in my project to add the "PublicDependencyModuleNames.AddRange(new string[] { "Blu" });" too ....

I do see the plugin in the list but still get the "Missing module" error...

**Comment by getnamo** [comment]
You don't have to strictly start them in blueprint. You can change a blueprint project into a C++ one via File->Add Code -> Empty Class

**Comment by DunkenKBliths** [comment]
Ah...just trying this now...thanks mate for your time...hopefully this will crack it...looking forward to having a play !

**Comment by DunkenKBliths** [comment]
(Really appreciating  your help..)
Ok...everything where is supposed to be (using the Visual2015 version of BLUI)...C++ class added... (now asking me to rebuild) ... loaded VS2015 re-building U4E works...my project ....gets

![image](https://cloud.githubusercontent.com/assets/12229031/13341777/878e110c-dc8b-11e5-85c5-4d87700959b6.png)

**Comment by AaronShea** [comment]
I'm going to close this issue as I've tested with UE 4.10+ and it functions just fine.
As for that error, regenerate your project files, and do a clean rebuild
