### ISSUE TITLE
Event reply needs to return a value

### ISSUE THREAD

**Issue by Youdaman** [AaronShea/BLUI#69]
Just a heads up that when following the setup instructions here: https://github.com/AaronShea/BLUI/wiki/Simple-Setup-(Windows-64-Bit)

You might need to add one more step about making the 4 Return nodes have a Return Value (I just used Unhandled, not sure what the difference is, but I think Handled messed with clicks bubbling up).

Screenshot of BLUI example blueprint complaining:
![screenshot 2016-03-14 12 22 19](https://cloud.githubusercontent.com/assets/287330/13732994/c7168040-e9e0-11e5-8d96-88bf6b9e2c0b.png)

**Comment by AaronShea** [comment]
I'll hopefully be fixing this in the next release that includes some bug fixes and (if I can get it on time) a newer build of Chromium/CEF3. It's spring break this week so I should definitely be getting around to it.
