### ISSUE TITLE
Example for RTCDataChannel?

### ISSUE THREAD

**Issue by SkaveRat** [AaronShea/BLUI#70]
I'd love to do data transfer (send and receive) with RTCDataChannel, but I can't really grasp on how to do this in BLUI/UE4.

If I pass the channel back to UE4, what type will it be, if possible at all?

**Comment by AaronShea** [comment]
We don't really have something to nicely wrap a class of that type in UE4's C++
While I believe that it could be done, it's not something that's built into BLUI at the moment.
