### ISSUE TITLE
Demo BLUIRoom 4.10 does not save in-game panels "visibility"

### ISSUE THREAD

**Issue by kallex** [AaronShea/BLUI#72]
I played with the Demo project room and brought the content to 4.10.4 UE. Everything works fine initially; the panes are visible. However after the room file is saved, it doesn't save the X orientation and Blend Mode properly. Those can be manually reverted back, but again once the project is closed and reopened, the changes are lost.

I've attached the screenshots of the properties after the load, and the final one as they should be; the visible white pane.

I'm not experienced enough to understand whether this is bug with UE component or BLUI. Will go dig into the code after submitting this issue to find out :-)

![screenshot 2016-03-25 16 05 49](https://cloud.githubusercontent.com/assets/674912/14045501/852e3526-f2a3-11e5-99e6-bd8430404366.png)

^ See the X-axis rotation transform; should be 90

![screenshot 2016-03-25 16 05 59](https://cloud.githubusercontent.com/assets/674912/14045500/852c051c-f2a3-11e5-882e-e83fb3c5759f.png)

^ See the Blend Mode; should be Transparent

![screenshot 2016-03-25 16 06 12](https://cloud.githubusercontent.com/assets/674912/14045499/852b3e16-f2a3-11e5-987a-97533d6b6472.png)

^ This how it looks like when they're properly set.

**Comment by kallex** [comment]
Note; the blueprint needs to be changed in some way to be saved after bringing the content to 4.10. If it's not changed (the file is not saved) it keeps working even after exiting and restarting the editor.

**Comment by kallex** [comment]
It seems to be related to Display-class (included in the demo blueprints) property recheck and save. Seems to work now OK

**Comment by AaronShea** [comment]
Sorry for not getting to your issues sooner, dealing with exams!
Glad you were able to fix it up. I've seen this before myself when upgrading the demo engine version. I've really been meaning to get to upgrading that!
