### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by getnamo** [AaronShea/BLUI#74]
WebGL seems to be disabled by default in BLUI. I suggest adding a toggle to enable webgl support on the main blu object?

see http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11568 for details on how to launch CEF with WebGL enabled.

**Comment by AaronShea** [comment]
Have you been able to enable WebGL on your local machine?
I'm unable to make it function from my testing so far actually. It may be due to the use of off-screen rendering. I'll look more into this.

**Comment by AaronShea** [comment]
Actually, this is all resolved in 220e6d9115db980d023938fc8015ee836956272b

**Comment by getnamo** [comment]
Awesome work!
