### ISSUE TITLE
cannot refresh or rebuild c++

### ISSUE THREAD

**Issue by thibaultpaysal** [AaronShea/BLUI#75]
Hello,

Your plugin looks great but unfortunately i got errors.

So i use unreal engine 4.10.4
I create a c++ unreal engine level and put the plugin BLUI inside my file directory. 
I try to refresh visual studio project and i got this awnser :

_
An error occurred while trying to generate project files.

Running D:/program files/epicgames/Epic Games/4.10/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="E:/unreal engine ressources/unreal engine project/blui2/blui2.uproject" -game -rocket -progress -2015
Discovering modules, targets and source code for game...
ERROR: Unable to instantiate instance of 'Blu' object type from compiled assembly 'blui2ModuleRules'.  Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requirements.  The CLR exception details may provide more information:  System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'E:\unreal engine ressources\unreal engine project\blui2\Plugins\BLUI-master\ThirdParty\cef\Win\shipping'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   à Blu..ctor(TargetInfo Target) dans e:\unreal engine ressources\unreal engine project\blui2\Plugins\BLUI-master\Source\Blu\Blu.Build.cs:ligne 63
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(Type type, Object[] args)
   à UnrealBuildTool.RulesCompiler.RulesAssembly.CreateModuleRules(String ModuleName, TargetInfo Target, String& ModuleFileName)
_

So i gone in visual studio and i tryed to rebuild the project and i get this : 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""D:\program files\epicgames\Epic Games\4.10\Engine\Build\BatchFiles\Clean.bat" blui2Editor Win64 Development "E:\unreal engine ressources\unreal engine project\blui2\blui2.uproject" -rocket -waitmutex -2015" exited with code -1.	blui2	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	32	

and this 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to instantiate instance of 'Blu' object type from compiled assembly 'blui2ModuleRules'.  Unreal Build Tool creates an instance of your module's 'Rules' object in order to find out about your module's requirements.  The CLR exception details may provide more information:  System.Reflection.TargetInvocationException: Une exception a ├®t├® lev├®e par la cible d'un appel. ---> System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'acc├¿s 'E:\unreal engine ressources\unreal engine project\blui2\Plugins\BLUI-master\ThirdParty\cef\Win\shipping'.	blui2	E:\unreal engine ressources\unreal engine project\blui2\Intermediate\ProjectFiles\EXEC	1	

Can you help me please because i would like to include your plugin in my project.
Thank you

**Comment by AaronShea** [comment]
You downloaded the master zip, this does not include the binary distribution of Chromium Framework.
Please use the **Release** tab.
