### ISSUE TITLE
GetMaterialInstance node not available

### ISSUE THREAD

**Issue by MagicIndustries** [AaronShea/BLUI#77]
I've been following this video: https://www.youtube.com/watch?v=VCPhsxd5rTE and it uses a BLU node called GetMaterialInstance. No matter what I do I can't seem to find that node (everything else works fine).

Is the video out of date? Or is there something else wrong?

**Comment by AaronShea** [comment]
Yeah, this node was deprecated.
I think we talked about this over email.
