### ISSUE TITLE
I working with UE4 .15,But I only can get release BLUI 3.1

### ISSUE THREAD

**Issue by zongtonggui** [AaronShea/BLUI#99]
BLUI 3.1 is working with UE 4.10.  But I need working with UE 4.15. Who can give me a more advanced version? I see people working at 4.15。

**Comment by getnamo** [comment]
You can add the plugin to a C++ project and recompile and it will update the plugin to 4.15. Just use the master branch code which has 4.15 code fixes.

**Comment by zongtonggui** [comment]
@getnamo  thanks for your help. And I can't download BLUI 3.1 or 3.0.    Maybe  I  should to copy the master branch code of BLUI into Plugin Folder in my project?

**Comment by zongtonggui** [comment]
I am  ashamed of it .I don't know much about Github.
